# Copyright (c) 2016-2022 Martin Donath <martin.donath@squidfunk.com>

# Project information
site_name: Home
site_url: https://github.com/fralfaro/python_sdk
site_author: Francisco Alfaro
site_description:

# Repository
repo_name: fralfaro/python_sdk
repo_url: https://github.com/fralfaro/python_sdk
edit_uri: ''

# TOC
nav:
    - Home: index.md
    - Setup:
      - Pyenv: setup/pyenv.md
      - Venv: setup/virtualenv.md
      - Poetry: setup/poetry.md
    - OOP:
      - Introducción: oop/oop.md
      - Conceptos Básicos: oop/oop_conceptos_basicos.ipynb
      - Herencia: oop/oop_herencia.ipynb
      - Cohesion: oop/oop_cohesion.ipynb
      - Abstraccion: oop/oop_abstraccion.ipynb
      - Polimorfismo: oop/oop_polimorfismo.ipynb
      - Acoplamiento: oop/oop_acoplamiento.ipynb
      - Encapsulamiento: oop/oop_encapsulamiento.ipynb





# Markdown extensions
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences

# Extra javascript
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Theme
theme:
  name: material
  language: es
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: blue grey
    accent: amber
    toggle:
      icon: material/lightbulb
      name: Switch to light mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: blue grey
    accent: amber
    toggle:
      icon: material/lightbulb-outline
      name: Switch to dark mode

extra_css:
  - stylesheets/extra.css