# Project information
site_name: Home
site_url: https://github.com/fralfaro/python_sdk
site_author: Francisco Alfaro
site_description:

# Repository
repo_name: fralfaro/python_sdk
repo_url: https://github.com/fralfaro/python_sdk
edit_uri: ''


# Markdown extensions
markdown_extensions:
  - attr_list
  - admonition
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tabbed

# Extra javascript
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Theme
theme:
  name: material
  language: es
  logo: images/sdk.png
  favicon: images/logo_fam.png
  features:
    - navigation.instant
    - navigation.top
    - content.code.annotate
    - search.suggest
    - search.highlight
  palette:
    # Light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: white
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: black
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/fralfaro
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.com/fralfaro
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/faam/
    - icon: fontawesome/brands/kaggle
      link: https://www.kaggle.com/faamds
    - icon: fontawesome/brands/medium
      link: https://medium.com/@fralfaro
    - icon: fontawesome/solid/globe
      link: https://fralfaro.github.io/portfolio/

# Plugins
plugins:
  - mkdocs-jupyter:
      kernel_name: python3
  - search

# TOC
nav:
    - index.md
    - Setup:
        - Pyenv: setup/pyenv.md
        - Virtualenv: setup/virtualenv.md
        - Poetry: setup/poetry.md
        - Git:
            - git/git.md
            - Gitignore: git/gitignore.md
        - GitHub:
            - git/github.md
            - Licensing: git/licensing.md
    - Programming:
        - S.O.L.I.D.: programming/solid.md
        - Design Patterns: programming/design_pattern.md
        - Refactoring: programming/refactoring.md
    - Ecosystem:
        - P.E.P.: programming/pep.md
        - Programming Paradigms:
            - Introduction: programming/paradigm.md
            - Functions: programming/function.md
            - Classes: programming/classes.md
        - Typing: ecosystem/typing.md
        - Pydantic: ecosystem/pydantic.md
    - Utilities:
        - Logging: utilities/logging.md
        - Styling: utilities/styling.md
        - Pre-commit: utilities/precommit.md
    - Testing:
        - Introduction: testing/intro.md
        - Pytest: testing/pytest.md
        - Coverage: testing/coverage.md
        - Mocking: testing/mocking.md
        - Hypothesis: testing/hypothesis.md
    - Documentation:
        - Introduction: documentation/intro.md
        - Mkdocs: documentation/mkdocs.md
        - Mkdocs-Material: documentation/mkdocs-material.md
        - Mkdocs-Plugging: documentation/mkdocs-plugging.md
    - Extras:
        - diagrams/plantuml.ipynb
        - diagrams/diagrams.ipynb
        - MakeFile: setup/makefile.md

