# Copyright (c) 2016-2022 Martin Donath <martin.donath@squidfunk.com>

# Project information
site_name: Home
site_url: https://github.com/fralfaro/python_sdk
site_author: Francisco Alfaro
site_description:

# Repository
repo_name: fralfaro/python_sdk
repo_url: https://github.com/fralfaro/python_sdk
edit_uri: ''

# TOC
nav:
    - Home: index.md
    - Setup:
      - Pyenv: setup/pyenv.md
      - Venv: setup/virtualenv.md
      - Poetry: setup/poetry.md
    - OOP:
      - Introducci칩n: oop/oop.md
      - Conceptos B치sicos: oop/oop_conceptos_basicos.md
      - Herencia: oop/oop_herencia.md
      - Cohesion: oop/oop_cohesion.md
      - Abstraccion: oop/oop_abstraccion.md
      - Polimorfismo: oop/oop_polimorfismo.md
      - Acoplamiento: oop/oop_acoplamiento.md
      - Encapsulamiento: oop/oop_encapsulamiento.md
    - Pr치cticas:
      - Dise침o de Patrones: pragmatic/patterns/intro.md
        - Patrones:
            - creacionales: pragmatic/patterns/creacionales.md
            - estructurales: pragmatic/patterns/estructurales.md
            - comportamiento: pragmatic/patterns/comportamiento.md
      - SOLID: pragmatic/solid/intro.md
        - Principios:
            - solid1: pragmatic/solid/1_srp.md
            - solid2: pragmatic/solid/2_ocp.md
            - solid3: pragmatic/solid/3_lsp.md
            - solid4: pragmatic/solid/4_isp.md
            - solid5: pragmatic/solid/5_dip.md


# Markdown extensions
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences

# Extra javascript
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Theme
theme:
  name: material
  language: es
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: blue grey
    accent: amber
    toggle:
      icon: material/lightbulb
      name: Switch to light mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: blue grey
    accent: amber
    toggle:
      icon: material/lightbulb-outline
      name: Switch to dark mode

extra_css:
  - stylesheets/extra.css